### ISSUE TITLE
how to obtain code for I3D and I3D+GCN implementations by [21] in your paper?

### ISSUE THREAD

**Issue by rohitsaluja22** [valeoai/BEEF#1]
Hi, thanks for sharing the code. Is it possible for you to share how to obtain code for I3D and I3D+GCN implementations by [21] you used in your paper?

**Comment by EloiZ** [comment]
Hello,
We reported the results directly from their paper: https://arxiv.org/abs/1909.09272

**Comment by rohitsaluja22** [comment]
I see, thanks for your reply.
