### ISSUE TITLE
absence of train.txt and val.txt on https://usa.honda-ri.com/HDD

### ISSUE THREAD

**Issue by rohitsaluja22** [valeoai/BEEF#2]
Hi, we downloaded HDD data from https://usa.honda-ri.com/HDD after submitting the required documents. We are trying to replicate the results of Table1 in your paper. 

We could not find train.txt and val.txt in downloaded HDD Data as shared in your readme.

It would be great if you can help us with the files or their sample contents/explaination on how to create them.

Thanks
Rohit

**Comment by Hediby** [comment]
Hi,

In the dataset you just downloaded from Honda's website, there should be a `EAF_Parsing/cfg.py` file. In this python file, you will find a class named `GeneralCfg`, which has the attributes `self.train_session_set` and `self.validation_session_set`. These attributes, manually defined in the `__init__` method, contain the ids for train and val sets. We basically copy/pasted these ids in `train.txt` and `val.txt`, which we found more convenient to manipulate. More precisely, our files look like this:

```
# head HDD/train.txt
201702271017
201702271123
201702271136
201702271438
201702271632
201702281017
201702281511
201702281709
```

Let me know if it is ok.

**Comment by rohitsaluja22** [comment]
Hi @Hediby, thank you for your reply. The information was helpful :)

Rohit

**Comment by rohitsaluja22** [comment]
Also, it would be great if you can help me understand the contents of json files in Processed folder, e.g.:

what are xy, prev_xy, next_xy, r_prev_xy, r_next_xy? Blinkners are not used for multi_head model in table 1 of your paper, right?
why are labels "-1", and blinkers : "" for many of the signals? (I understand labels list in cache_data['event_type_ix'].items(), is -1 label for driving straight? I perhaps also understand that blinkers are "" because that means straight driving!)

**Comment by rohitsaluja22** [comment]
Hi, I got my answers after analyzing datasets/hdd.py.
Thanks, you may close the issue.
