### ISSUE TITLE
BDDX-Video Clips

### ISSUE THREAD

**Issue by varungupta31** [valeoai/BEEF#4]
Hey, I request your help with something slightly off-topic, i.e. obtaining the video clips used in the BDD-X paper.
The [BDDX-Project Page](https://github.com/JinkyuKimUCB/BDD-X-dataset) doesn't have the video dataset available, only the explanation text CSV.

Could you possibly help with how to access those videos?

Thanks!

**Comment by EloiZ** [comment]
Hello,
BDDX is built on top of BDD, it just provides some extra annotations as well as train/val/test splits.
Original BDD data can be accessed here : https://bdd-data.berkeley.edu/

**Comment by varungupta31** [comment]
Thanks for the reply @EloiZ.
I'm indeed aware that BDDX is a subset of BDD.

The following image is from the annotation CSV in BDDX
![image](https://user-images.githubusercontent.com/51288316/203291094-224e15d0-bcd3-4522-a6e2-86ac028f1534.png)

If I wish to train a model on the same video clips or observe the annotation with the videos, is there a way I can reference which video they mean by the AWS link? BDD is a huge dataset and  I can't find which videos from BDD they used and provided the corresponding annotations.

**Comment by EloiZ** [comment]
We followed instructions in https://github.com/JinkyuKimUCB/explainable-deep-driving
I think the answer is in the two following files:
Steps 0 https://github.com/JinkyuKimUCB/explainable-deep-driving/blob/master/Step0_download_BDDVdata.py
Steps 1 https://github.com/JinkyuKimUCB/explainable-deep-driving/blob/master/Step1_preprocessing.py

Let me know if that works

**Comment by varungupta31** [comment]
I tried that earlier, but the  Script gives a `Forbidden Error`. Following is the error:

```
  File "/home/varun/miniconda3/envs/iddx/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

[Some articles](https://bobcares.com/blog/wget-403-forbidden/)  suggested providing a `--user-agent` flag, but that didn't resolve the error as well.

Running `wget --user-agent="Mozilla" https://s3-us-west-2.amazonaws.com/sq8geewpqu/samples-1k/06d501fd-a9ffc960.mov`
resulted in the following traceback:


```
--2022-11-22 18:44:30--  https://s3-us-west-2.amazonaws.com/sq8geewpqu/samples-1k/06d501fd-a9ffc960.mov
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.234.152, 52.92.178.56, 52.92.165.0, ...
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.234.152|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-11-22 18:44:33 ERROR 403: Forbidden.
```



a. Did you make any modifications to the URL or the Script to get it working?
b. Do you by chance, still have the dataset? 


Ps - I completely understand that this topic may be out-of-topic for you to deal with. The BDDX authors fail to respond, So I hope you'll be able to help me out :)

**Comment by EloiZ** [comment]
I have the same error, maybe they've moved data somewhere else.
We don't have the data anymore unfortunately and I cannot rememeber or find how we downloaded it in the first place. Sorry about it.
I hope the authors will answer you and fix it!

**Comment by varungupta31** [comment]
cool, thanks for the help.
